# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-26.04
  image: ubuntu:26.04
  package: deb
  check-manifest-suite: ubuntu-26.04-amd64

build-images:
- label: ubuntu
  base-image: ubuntu:26.04
  package: deb
  artifact-from: ubuntu-26.04

smoke-tests:
- label: ubuntu

scan-vulnerabilities:
- label: ubuntu

release-packages:

release-images:
- label: ubuntu
  package: deb
